# Logo
logo_image_source: http://www.codeblocq.com/assets/projects/hexo-theme-anodyne/assets/anodyne.svg

# Index Page
index_banner_text: Tom's Code Garden
index_banner_text_secondary: Make Magic.
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Home: /
  JS: /categories/Javascript
  Categories: /categories
  Tags: /tags
  About: /about

widgets:
- search
- category

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: http://img.tukexw.com/img/ee963fc9e2da33b2.jpg
about_widget_text: "Hi this is TomZhao, still a junior developer. <br>Welcome!"


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: https://github.com/tomzhao001/toms-personal-blog
    fa_icon: fa-github
  - url: mailto:tomzhao001@hotmail.com
    fa_icon: fa-envelope
  - url: /#
    fa_icon: fa-rss

# Footer about
footer_about: "@TomZhao. All right reserved"
